import React, { useEffect, useMemo, useState } from 'react';
import { ChevronRight, FileText, Upload, CheckCircle, Search, Filter, Send, Paperclip, X, RefreshCw, Download } from 'lucide-react';
import { getMyStudentProfile, getMyProject, getMySubmissions, createSubmission } from '../../services/studentService';
import { getAvailableTopics, selectProjectTopic, proposeProjectTopic } from '../../services/topicService';
import { getMyProgress, updateMyProgress } from '../../services/progressService';
import { getSubmissionFeedback } from '../../services/feedbackService';
import { uploadProjectDocument, createDocumentDownloadUrl } from '../../services/storageService';
import { getConversation, sendMessage, markConversationRead, subscribeToMessages } from '../../services/messageService';

interface ScreenProps { onNavigate: (screen: string) => void; }
const fmtDate = (value?: string) => value ? new Date(value).toLocaleString() : '—';
const initials = (name?: string) => (name || 'User').split(' ').map(x => x[0]).slice(0,2).join('').toUpperCase();
const errorText = (e: any) => e?.message || 'Something went wrong. Please try again.';

function StatusBadge({ status }: { status?: string }) {
  const label = (status || 'pending').replace('_', ' ');
  return <span className="px-2 py-1 bg-[#EEEDFB] text-[#312DC4] text-xs rounded-full border border-[#C5C3EC] capitalize">{label}</span>;
}
function PageTitle({ title, onNavigate }: { title: string; onNavigate: (s:string)=>void }) {
  return <div className="flex items-center text-sm text-gray-500 mb-4"><button onClick={() => onNavigate('dashboard')} className="hover:underline">Home</button><ChevronRight className="w-4 h-4 mx-2"/><span className="text-gray-900">{title}</span></div>;
}
function FeedbackList({ feedback }: { feedback: any[] }) {
  if (!feedback?.length) return <p className="text-sm text-gray-400">No feedback yet.</p>;
  return <div className="space-y-2">{feedback.map(item => <div key={item.id} className="p-3 bg-gray-50 rounded-md"><p className="text-sm text-gray-700">{item.comment}</p><p className="text-xs text-gray-400 mt-1">{item.lecturers?.profiles?.full_name || 'Supervisor'} · {fmtDate(item.created_at)}</p></div>)}</div>;
}

export function StudentDashboard({ onNavigate }: ScreenProps) {
  const [profile, setProfile] = useState<any>(null), [project, setProject] = useState<any>(null), [submissions, setSubmissions] = useState<any[]>([]), [progress, setProgress] = useState<any>(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  async function load() { try { setLoading(true); setError(''); const [p, a, s, pr] = await Promise.all([getMyStudentProfile(), getMyProject(), getMySubmissions(), getMyProgress()]); setProfile(p); setProject(a); setSubmissions(s); setProgress(pr); } catch(e){setError(errorText(e));} finally{setLoading(false);} }
  useEffect(()=>{load();},[]);
  const latest = submissions[0];
  return <div className="space-y-6 max-w-5xl mx-auto">
    <PageTitle title="Student Dashboard" onNavigate={onNavigate}/>
    <div className="flex justify-between items-end"><div><h1 className="text-2xl font-bold text-gray-800">Welcome, {profile?.profiles?.full_name || 'Student'}</h1><p className="text-gray-500">Overview of your final year project.</p></div><button onClick={load} className="p-2 text-gray-500 hover:bg-gray-100 rounded-md" title="Refresh"><RefreshCw className="w-4 h-4"/></button></div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">{error}</div>}
    {loading ? <div className="p-10 text-center text-gray-500">Loading dashboard...</div> : <>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6"><div className="col-span-1 md:col-span-2 space-y-6">
        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="text-lg font-semibold text-gray-800 mb-4">Current Project</h2><div className="space-y-3"><div><p className="text-sm text-gray-500">Topic</p><p className="font-medium text-gray-900">{project?.project_topics?.title || 'No project topic selected'}</p></div><div><p className="text-sm text-gray-500">Assigned Supervisor</p><p className="font-medium text-gray-900">{project?.lecturers?.profiles?.full_name || 'Not assigned'}</p></div><div><p className="text-sm text-gray-500">Allocation Status</p><StatusBadge status={project?.status}/></div></div></div>
        <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><div className="flex justify-between items-center mb-4"><h2 className="text-lg font-semibold text-gray-800">Latest Submission</h2><button onClick={()=>onNavigate('submission')} className="text-sm text-[#312DC4] hover:underline">View All</button></div>{latest ? <div className="flex items-center justify-between p-4 border border-gray-200 rounded-md bg-gray-50"><div className="flex items-center gap-3"><FileText className="w-5 h-5 text-gray-400"/><div><p className="font-medium text-sm">{latest.title}</p><p className="text-xs text-gray-500">{latest.chapter || 'Submission'} · {fmtDate(latest.submitted_at)}</p></div></div><StatusBadge status={latest.status}/></div> : <p className="text-sm text-gray-400">No submissions yet.</p>}</div>
      </div><div className="space-y-6"><div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="text-lg font-semibold text-gray-800 mb-4">Overall Progress</h2><div className="flex items-center justify-center"><div className="relative w-32 h-32 flex items-center justify-center bg-[#EEEDFB] rounded-full border-4 border-[#312DC4]"><span className="text-2xl font-bold text-[#312DC4]">{progress?.percentage ?? 0}%</span></div></div><button onClick={()=>onNavigate('progress')} className="w-full mt-6 py-2 bg-[#EEEDFB] hover:bg-[#E3E2F7] text-[#312DC4] text-sm font-medium rounded-md">View Detailed Progress</button></div><div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="text-lg font-semibold text-gray-800 mb-4">Profile</h2><p className="text-sm text-gray-700">{profile?.profiles?.full_name}</p><p className="text-xs text-gray-500 mt-1">{profile?.matric_number} · {profile?.department}</p><button onClick={()=>onNavigate('messages')} className="w-full mt-4 py-2 border border-gray-300 hover:bg-gray-50 text-gray-700 text-sm font-medium rounded-md">Message Supervisor</button></div></div></div>
      <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="text-lg font-semibold text-gray-800 mb-4">Quick Actions</h2><div className="flex flex-wrap gap-4"><button onClick={()=>onNavigate('topic-selection')} className="px-4 py-2 bg-[#312DC4] text-white rounded-md text-sm font-medium">Browse Project Topics</button><button onClick={()=>onNavigate('submission')} className="px-4 py-2 border border-gray-300 text-gray-700 rounded-md text-sm font-medium">Submit Chapter</button><button onClick={()=>onNavigate('messages')} className="px-4 py-2 border border-gray-300 text-gray-700 rounded-md text-sm font-medium">Message Supervisor</button></div></div>
    </>}
  </div>;
}

export function ProjectTopicSelection({ onNavigate }: ScreenProps) {
  const [topics,setTopics]=useState<any[]>([]),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[area,setArea]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selecting,setSelecting]=useState<string|null>(null); const [proposal,setProposal]=useState({title:'',description:'',researchArea:''}); const [saving,setSaving]=useState(false);
  async function load(){try{setLoading(true);setError('');setTopics(await getAvailableTopics(department||undefined));}catch(e){setError(errorText(e));}finally{setLoading(false);}} useEffect(()=>{load();},[department]);
  const departments=useMemo(()=>Array.from(new Set(topics.map(t=>t.department).filter(Boolean))),[topics]); const areas=useMemo(()=>Array.from(new Set(topics.map(t=>t.research_area).filter(Boolean))),[topics]); const filtered=topics.filter(t=>`${t.title} ${t.description} ${t.research_area||''}`.toLowerCase().includes(search.toLowerCase()) && (!area||t.research_area===area));
  async function choose(id:string){try{setSelecting(id);await selectProjectTopic(id);alert('Topic request submitted successfully.');onNavigate('dashboard');}catch(e){setError(errorText(e));}finally{setSelecting(null);}}
  async function propose(){if(!proposal.title.trim()||!proposal.description.trim()){setError('Topic title and description are required.');return;}try{setSaving(true);await proposeProjectTopic({...proposal,department:department||'Unspecified'});alert('Your topic proposal has been submitted for approval.');setProposal({title:'',description:'',researchArea:''});}catch(e){setError(errorText(e));}finally{setSaving(false);}}
  return <div className="space-y-6 max-w-5xl mx-auto"><PageTitle title="Project Topics" onNavigate={onNavigate}/><h1 className="text-2xl font-bold text-gray-800">Project Topic Selection</h1>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">{error}</div>}<div className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm flex flex-wrap gap-4 items-center"><div className="relative flex-1 min-w-[200px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search topics..." className="w-full bg-gray-50 border border-gray-300 rounded-md py-2 pl-10 pr-4 text-sm"/></div><Filter className="w-4 h-4 text-gray-500"/><select value={department} onChange={e=>setDepartment(e.target.value)} className="border border-gray-300 rounded-md py-2 px-3 text-sm bg-gray-50"><option value="">All Departments</option>{departments.map(d=><option key={d}>{d}</option>)}</select><select value={area} onChange={e=>setArea(e.target.value)} className="border border-gray-300 rounded-md py-2 px-3 text-sm bg-gray-50"><option value="">All Research Areas</option>{areas.map(a=><option key={a}>{a}</option>)}</select></div>
  <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 border-b border-gray-200"><tr>{['Title & Description','Lecturer','Area of Specialization','Slots','Action'].map(h=><th key={h} className="px-4 py-3 font-medium text-gray-700">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{loading?<tr><td colSpan={5} className="p-8 text-center text-gray-500">Loading topics...</td></tr>:filtered.length===0?<tr><td colSpan={5} className="p-8 text-center text-gray-500">No topics found.</td></tr>:filtered.map(item=><tr key={item.id} className="hover:bg-gray-50"><td className="px-4 py-4"><p className="font-medium text-gray-900">{item.title}</p><p className="text-gray-500 mt-1 line-clamp-2">{item.description}</p></td><td className="px-4 py-4 text-gray-700 whitespace-nowrap">{item.lecturers?.profiles?.full_name||'—'}</td><td className="px-4 py-4"><span className="inline-block px-2 py-1 text-xs bg-[#EEEDFB] text-[#312DC4] rounded-full border border-[#C5C3EC]">{item.research_area||'General'}</span></td><td className="px-4 py-4 text-gray-700 whitespace-nowrap">{item.max_students}</td><td className="px-4 py-4 text-right"><button disabled={!!selecting} onClick={()=>choose(item.id)} className="px-3 py-1.5 bg-[#312DC4] text-white rounded-md text-sm disabled:opacity-50">{selecting===item.id?'Selecting...':'Select'}</button></td></tr>)}</tbody></table></div></div>
  <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="text-lg font-semibold text-gray-800 mb-4">Propose Your Own Topic</h2><div className="space-y-4 max-w-2xl"><input value={proposal.title} onChange={e=>setProposal({...proposal,title:e.target.value})} className="w-full border border-gray-300 rounded-md py-2 px-3 text-sm" placeholder="Topic title"/><textarea value={proposal.description} onChange={e=>setProposal({...proposal,description:e.target.value})} className="w-full border border-gray-300 rounded-md py-2 px-3 text-sm" rows={4} placeholder="Describe your proposed topic"/><input value={proposal.researchArea} onChange={e=>setProposal({...proposal,researchArea:e.target.value})} className="w-full border border-gray-300 rounded-md py-2 px-3 text-sm" placeholder="Research area (optional)"/><button disabled={saving} onClick={propose} className="px-4 py-2 bg-[#312DC4] text-white rounded-md text-sm disabled:opacity-50">{saving?'Submitting...':'Submit Proposal'}</button></div></div></div>;
}

export function SubmissionAndFeedback({ onNavigate }: ScreenProps) {
  const [submissions,setSubmissions]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[chapter,setChapter]=useState(''),[description,setDescription]=useState(''),[uploading,setUploading]=useState(false),[downloads,setDownloads]=useState<Record<string,string>>({});
  async function load(){try{setLoading(true);setSubmissions(await getMySubmissions());}catch(e){setError(errorText(e));}finally{setLoading(false);}} useEffect(()=>{load();},[]);
  async function submit(){if(!title.trim()){setError('Submission title is required.');return;}try{setUploading(true);setError('');let path:string|undefined;if(file){const student=await getMyStudentProfile();path=await uploadProjectDocument(file,student.id);}await createSubmission({title,chapter,description,filePath:path});setTitle('');setChapter('');setDescription('');setFile(null);await load();alert('Submission uploaded successfully.');}catch(e){setError(errorText(e));}finally{setUploading(false);}}
  async function download(path:string,id:string){try{const url=await createDocumentDownloadUrl(path);setDownloads({...downloads,[id]:url});window.open(url,'_blank','noopener,noreferrer');}catch(e){setError(errorText(e));}}
  return <div className="space-y-6 max-w-5xl mx-auto"><PageTitle title="Submissions" onNavigate={onNavigate}/><h1 className="text-2xl font-bold text-gray-800">Submission & Feedback</h1>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">{error}</div>}<div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm"><h2 className="font-semibold mb-4">Submit a Chapter</h2><div className="grid md:grid-cols-2 gap-4"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Submission title" className="border rounded-md p-2 text-sm"/><input value={chapter} onChange={e=>setChapter(e.target.value)} placeholder="Chapter e.g. Chapter 2" className="border rounded-md p-2 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" rows={3} className="border rounded-md p-2 text-sm md:col-span-2"/><label className="md:col-span-2 border border-dashed rounded-md p-4 text-sm text-gray-500 flex items-center gap-3 cursor-pointer"><Upload className="w-5 h-5"/><span>{file?file.name:'Choose project document'}</span><input type="file" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><button onClick={submit} disabled={uploading} className="mt-4 px-4 py-2 bg-[#312DC4] text-white rounded-md text-sm disabled:opacity-50">{uploading?'Submitting...':'Submit'}</button></div>
  <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden"><div className="p-6"><h2 className="font-semibold">Submission History</h2></div>{loading?<p className="p-6 text-gray-500">Loading...</p>:submissions.length===0?<p className="p-6 text-gray-500">No submissions yet.</p>:<div className="divide-y">{submissions.map(s=><div key={s.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium text-gray-900">{s.title}</h3><p className="text-xs text-gray-500 mt-1">{s.chapter||'Submission'} · {fmtDate(s.submitted_at)}</p></div><StatusBadge status={s.status}/></div>{s.description&&<p className="text-sm text-gray-600 mt-3">{s.description}</p>}{s.file_path&&<button onClick={()=>download(s.file_path,s.id)} className="mt-3 inline-flex items-center gap-2 text-sm text-[#312DC4] hover:underline"><Download className="w-4 h-4"/>Download document</button>}<div className="mt-4"><h4 className="text-sm font-medium mb-2">Feedback</h4><FeedbackList feedback={s.feedback||[]}/></div></div>)}</div>}</div></div>;
}

export function ProgressTracking({ onNavigate }: ScreenProps) {
  const [progress,setProgress]=useState<any>(null),[percentage,setPercentage]=useState(0),[stage,setStage]=useState(''),[description,setDescription]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function load(){try{setLoading(true);const p=await getMyProgress();setProgress(p);setPercentage(p?.percentage??0);setStage(p?.current_stage??'');setDescription(p?.description??'');}catch(e){setError(errorText(e));}finally{setLoading(false);}} useEffect(()=>{load();},[]);
  async function save(){try{setSaving(true);const p=await updateMyProgress({percentage,currentStage:stage,description});setProgress(p);alert('Progress updated successfully.');}catch(e){setError(errorText(e));}finally{setSaving(false);}}
  return <div className="space-y-6 max-w-5xl mx-auto"><PageTitle title="Progress Tracking" onNavigate={onNavigate}/><h1 className="text-2xl font-bold text-gray-800">Project Progress</h1>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">{error}</div>}{loading?<p className="text-gray-500">Loading progress...</p>:<div className="grid md:grid-cols-3 gap-6"><div className="bg-white p-6 rounded-lg border shadow-sm flex flex-col items-center"><div className="w-40 h-40 rounded-full border-8 border-[#312DC4] bg-[#EEEDFB] flex items-center justify-center"><span className="text-3xl font-bold text-[#312DC4]">{percentage}%</span></div><p className="mt-4 text-sm text-gray-500">Current stage: {stage||'Not specified'}</p></div><div className="md:col-span-2 bg-white p-6 rounded-lg border shadow-sm space-y-4"><label className="block text-sm font-medium">Progress percentage<input type="number" min={0} max={100} value={percentage} onChange={e=>setPercentage(Number(e.target.value))} className="mt-1 w-full border rounded-md p-2"/></label><label className="block text-sm font-medium">Current stage<input value={stage} onChange={e=>setStage(e.target.value)} className="mt-1 w-full border rounded-md p-2" placeholder="e.g. Literature Review"/></label><label className="block text-sm font-medium">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5} className="mt-1 w-full border rounded-md p-2"/></label><button onClick={save} disabled={saving} className="px-4 py-2 bg-[#312DC4] text-white rounded-md disabled:opacity-50">{saving?'Saving...':'Save Progress'}</button></div></div>}</div>;
}

export function StudentMessaging({ onNavigate }: ScreenProps) {
  const [profile,setProfile]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[input,setInput]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sending,setSending]=useState(false);
  const supervisorId=profile?.lecturers?.profiles?.id || profile?.lecturers?.user_id;
  async function load(){try{const p=await getMyProject();setProfile(p);if(p?.lecturers?.user_id){setMessages(await getConversation(p.lecturers.user_id));await markConversationRead(p.lecturers.user_id);}}catch(e){setError(errorText(e));}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!supervisorId)return;const channel=subscribeToMessages((payload:any)=>{const m=payload.new;if((m.sender_id===supervisorId||m.receiver_id===supervisorId)&&!messages.some(x=>x.id===m.id))setMessages(current=>[...current,m]);});return()=>{channel.unsubscribe();};},[supervisorId]);
  async function send(){if(!input.trim()||!supervisorId)return;try{setSending(true);const m=await sendMessage(supervisorId,input);setMessages(current=>[...current,m]);setInput('');}catch(e){setError(errorText(e));}finally{setSending(false);}}
  return <div className="max-w-5xl mx-auto flex flex-col" style={{height:'calc(100vh - 10rem)'}}><PageTitle title="Messages" onNavigate={onNavigate}/>{error&&<div className="p-2 mb-2 bg-red-50 text-red-700 rounded text-sm">{error}</div>}<div className="flex flex-1 min-h-0 bg-white rounded-lg border shadow-sm overflow-hidden"><aside className="w-72 border-r flex flex-col"><div className="p-4 border-b"><h2 className="font-semibold">Messages</h2></div><div className="p-4 text-sm bg-[#EEEDFB]"><p className="font-medium text-[#312DC4]">{profile?.lecturers?.profiles?.full_name||'Supervisor'}</p><p className="text-xs text-gray-500">Supervisor</p></div></aside><div className="flex-1 flex flex-col"><div className="h-16 flex items-center px-5 border-b"><div><p className="font-semibold">{profile?.lecturers?.profiles?.full_name||'Supervisor'}</p><p className="text-xs text-gray-400">{profile?.project_topics?.title||'Project supervisor'}</p></div></div><div className="flex-1 overflow-y-auto px-5 py-4 space-y-3 bg-gray-50/50">{loading?<p className="text-gray-500">Loading messages...</p>:messages.length===0?<p className="text-gray-400 text-sm">No messages yet. Start the conversation.</p>:messages.map(m=><div key={m.id} className={`flex ${m.sender_id===supervisorId?'justify-start':'justify-end'}`}><div className={`max-w-[70%] px-4 py-2.5 rounded-2xl text-sm ${m.sender_id===supervisorId?'bg-gray-100 text-gray-800 rounded-bl-sm':'bg-[#312DC4] text-white rounded-br-sm'}`}><p>{m.message}</p><span className="block text-[10px] opacity-60 mt-1">{fmtDate(m.created_at)}</span></div></div>)}</div><div className="px-4 py-3 border-t flex items-center gap-2"><Paperclip className="w-5 h-5 text-gray-400"/><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send();}} placeholder={supervisorId?'Type a message...':'Select a supervisor first'} disabled={!supervisorId} className="flex-1 bg-gray-100 rounded-full px-4 py-2 text-sm"/><button onClick={send} disabled={!input.trim()||sending||!supervisorId} className="p-2.5 rounded-full bg-[#312DC4] text-white disabled:bg-gray-200 disabled:text-gray-400"><Send className="w-4 h-4"/></button></div></div></div></div>;
}
